### ISSUE TITLE
https://ast.ninja/ opens elixir bootcamp website

### ISSUE THREAD

**Issue by bmarkons** [arjan/ast_ninja#9]
Hi,

Is there any place this can be tried out online?

Thanks :)

**Comment by arjan** [comment]
Yes, good idea. Ive had some server issues lately, will fix soon.

**Comment by arjan** [comment]
Working on it.. you can already run it yourself:

```
docker run --rm -it -p 4000:4000 acscherp/ast_ninja
```

**Comment by bmarkons** [comment]
Awesome! Thank you ❤️

**Comment by arjan** [comment]
And.. it's up again! https://ast.ninja/
